// Rich Mock Seed Data for Axion Intelligent Business Platform

export const MOCK_ORDERS = [
  {
    id: "ord_88219",
    orderNumber: "ORD-88219",
    customerName: "Aarav Sharma",
    customerEmail: "aarav.sharma@example.com",
    customerTier: "VIP",
    orderDate: "2026-08-28T10:30:00Z",
    totalAmount: 6499,
    status: "DELIVERED",
    items: [
      {
        sku: "SHOE-RUN-42",
        title: "Axion Velocity Pro Running Shoes (Cobalt Blue)",
        size: "UK 9",
        color: "Cobalt Blue",
        price: 6499,
        quantity: 1,
        returnWindowDays: 30,
        inStockAlternatives: ["UK 9.5", "UK 10"],
      },
    ],
  },
  {
    id: "ord_91044",
    orderNumber: "ORD-91044",
    customerName: "Priya Sundaram",
    customerEmail: "priya.s@example.com",
    customerTier: "GOLD",
    orderDate: "2026-08-30T14:15:00Z",
    totalAmount: 12999,
    status: "DELIVERED",
    items: [
      {
        sku: "AUDIO-NC-409",
        title: "Apex ANC Pro Wireless Headphones",
        size: "Standard",
        color: "Midnight Black",
        price: 12999,
        quantity: 1,
        returnWindowDays: 15,
        inStockAlternatives: [],
      },
    ],
  },
  {
    id: "ord_77103",
    orderNumber: "ORD-77103",
    customerName: "Devendra Patel",
    customerEmail: "dev.patel99@example.com",
    customerTier: "STANDARD",
    orderDate: "2026-08-15T09:00:00Z",
    totalAmount: 3299,
    status: "DELIVERED",
    items: [
      {
        sku: "APPAREL-MERINO-02",
        title: "Merino Wool Breathable Pullover",
        size: "L",
        color: "Heather Gray",
        price: 3299,
        quantity: 1,
        returnWindowDays: 14,
        inStockAlternatives: ["XL"],
      },
    ],
  },
];

export const MOCK_INVENTORY_SKUS = [
  {
    id: "sku_409",
    sku: "SKU-409",
    name: "Apex ANC Pro Wireless Headphones",
    category: "Consumer Audio",
    currentStock: 180,
    unitCost: 4800,
    sellingPrice: 12999,
    dailySalesRate: 20.0,
    daysToStockout: 9.0, // Product runs out in 9 days!
    reorderPoint: 220,
    reorderQuantity: 350,
    safetyStock: 80,
    status: "CRITICAL" as const,
    salesTrend: [18, 19, 21, 20, 22, 19, 24, 20, 23, 21, 22, 20, 25, 20],
    suppliers: [
      {
        id: "sup_a",
        name: "Supplier A (Shenzhen Precision Audio)",
        leadTimeDays: 14,
        unitCost: 4500,
        minOrderQuantity: 500,
        reliabilityScore: 0.88,
        isPreferred: false,
      },
      {
        id: "sup_b",
        name: "Supplier B (Bangalore FastTech Electronics)",
        leadTimeDays: 4,
        unitCost: 4750,
        minOrderQuantity: 250,
        reliabilityScore: 0.98,
        isPreferred: true,
      },
    ],
  },
  {
    id: "sku_102",
    sku: "SKU-102",
    name: "Axion Velocity Pro Running Shoes",
    category: "Footwear & Sports",
    currentStock: 450,
    unitCost: 2100,
    sellingPrice: 6499,
    dailySalesRate: 15.0,
    daysToStockout: 30.0,
    reorderPoint: 300,
    reorderQuantity: 400,
    safetyStock: 100,
    status: "HEALTHY" as const,
    salesTrend: [14, 15, 13, 16, 15, 14, 17, 15, 16, 14, 15, 18, 15, 16],
    suppliers: [
      {
        id: "sup_c",
        name: "Supplier Alpha Footwear",
        leadTimeDays: 10,
        unitCost: 2050,
        minOrderQuantity: 300,
        reliabilityScore: 0.94,
        isPreferred: true,
      },
      {
        id: "sup_d",
        name: "Supplier Beta Sole Works",
        leadTimeDays: 7,
        unitCost: 2200,
        minOrderQuantity: 200,
        reliabilityScore: 0.91,
        isPreferred: false,
      },
    ],
  },
  {
    id: "sku_305",
    sku: "SKU-305",
    name: "Urban Hydro-Shield Commuter Backpack",
    category: "Luggage & Gear",
    currentStock: 64,
    unitCost: 1400,
    sellingPrice: 4299,
    dailySalesRate: 8.0,
    daysToStockout: 8.0,
    reorderPoint: 90,
    reorderQuantity: 200,
    safetyStock: 30,
    status: "LOW_STOCK" as const,
    salesTrend: [6, 7, 8, 8, 9, 8, 7, 8, 9, 10, 8, 7, 9, 8],
    suppliers: [
      {
        id: "sup_e",
        name: "Apex Gear Craft Ltd",
        leadTimeDays: 6,
        unitCost: 1350,
        minOrderQuantity: 150,
        reliabilityScore: 0.95,
        isPreferred: true,
      },
      {
        id: "sup_f",
        name: "Global Pack Express",
        leadTimeDays: 3,
        unitCost: 1480,
        minOrderQuantity: 100,
        reliabilityScore: 0.96,
        isPreferred: false,
      },
    ],
  },
  {
    id: "sku_512",
    sku: "SKU-512",
    name: "Ultra-Fast 100W GaN Charging Hub",
    category: "Accessories",
    currentStock: 310,
    unitCost: 850,
    sellingPrice: 2899,
    dailySalesRate: 11.0,
    daysToStockout: 28.1,
    reorderPoint: 200,
    reorderQuantity: 300,
    safetyStock: 60,
    status: "HEALTHY" as const,
    salesTrend: [10, 11, 10, 12, 11, 13, 11, 10, 12, 11, 14, 10, 12, 11],
    suppliers: [
      {
        id: "sup_g",
        name: "PowerVolt Components",
        leadTimeDays: 8,
        unitCost: 820,
        minOrderQuantity: 250,
        reliabilityScore: 0.92,
        isPreferred: true,
      },
    ],
  },
];

export const MOCK_EXPENSES = [
  {
    id: "exp_101",
    claimNumber: "EXP-2026-891",
    employeeName: "Rohan Varma",
    employeeRole: "Senior Enterprise Account Executive",
    department: "Sales & Client Success",
    vendor: "Grand Hyatt Mumbai",
    category: "ACCOMMODATION",
    amount: 18400,
    currency: "INR",
    date: "2026-09-02",
    receiptUrl: "/receipts/hotel_hyatt_mumbai.pdf",
    status: "flagged" as const,
    confidence: 0.97,
    policyLimit: 12000,
    violations: [
      {
        rule: "Tier-1 Metro Accommodation Cap",
        severity: "HIGH" as const,
        description: "Claimed ₹18,400 per night exceeds the corporate standard cap of ₹12,000 for Senior Executives without pre-approval from VP Finance.",
      },
      {
        rule: "Mini-bar / Ancillary Charges",
        severity: "MEDIUM" as const,
        description: "Itemized receipt shows ₹2,400 in personal lounge/mini-bar expenses which are non-reimbursable.",
      },
    ],
    reasoning: "Hotel expense of ₹18,400 exceeds Tier-1 metro policy limit of ₹12,000 by ₹6,400 (53.3% variance). Flagged for manager exception approval or reduction to policy cap.",
    policyReference: "Travel & Expense Policy v3.2 (Section 4.1 - Domestic Lodging Caps)",
  },
  {
    id: "exp_102",
    claimNumber: "EXP-2026-892",
    employeeName: "Ananya Deshmukh",
    employeeRole: "Lead Cloud Infrastructure Engineer",
    department: "Engineering",
    vendor: "Datadog Cloud Monitoring",
    category: "SOFTWARE",
    amount: 82000,
    currency: "INR",
    date: "2026-09-01",
    receiptUrl: "/receipts/datadog_invoice.pdf",
    status: "approved" as const,
    confidence: 0.99,
    policyLimit: 100000,
    violations: [],
    reasoning: "Monthly pre-approved recurring infrastructure tooling invoice matching procurement purchase order PO-66321.",
    policyReference: "Procurement & SaaS Policy v2.0 (Section 2.3 - Cloud Tooling)",
  },
  {
    id: "exp_103",
    claimNumber: "EXP-2026-893",
    employeeName: "Vikram Malhotra",
    employeeRole: "Regional Logistics Manager",
    department: "Operations",
    vendor: "Blue Dart Express Logistics",
    category: "LOGISTICS",
    amount: 34500,
    currency: "INR",
    date: "2026-09-04",
    receiptUrl: "/receipts/bluedart_freight.pdf",
    status: "approved" as const,
    confidence: 0.96,
    policyLimit: 50000,
    violations: [],
    reasoning: "Urgent inventory transfer between Delhi hub and Bangalore fulfillment center within operational contingency budget.",
    policyReference: "Supply Chain Operations Budget Handbook 2026",
  },
];

export const MOCK_POLICIES = [
  {
    id: "pol_travel_01",
    title: "Axion Corporate Travel & Expense Policy v3.2",
    category: "TRAVEL_EXPENSE",
    content: `AXION ENTERPRISE REIMBURSEMENT POLICY (Effective Q3 2026)
1. ACCOMMODATION:
   - Tier-1 Metro Cities (Mumbai, Delhi-NCR, Bangalore): Max ₹12,000 per night inclusive of taxes for Senior Managers and Directors. Max ₹8,500 for Individual Contributors.
   - Tier-2 Cities (Pune, Hyderabad, Chennai, Kolkata): Max ₹8,000 per night.
   - Non-reimbursable: Mini-bar charges, in-room movies, spa, dry cleaning under 4 nights stay.
2. MEALS & CLIENT ENTERTAINMENT:
   - Daily Meal Allowance during travel: Max ₹2,500 per day.
   - Client Entertainment Dinner: Max ₹5,000 per attendee, itemized tax invoice mandatory.
3. FLIGHTS & RAIL:
   - Domestic Travel: Economy class standard on all sectors under 5 hours.
4. SOFTWARE & SUBSCRIPTIONS:
   - Requires IT and Department Head pre-approval. Single items over ₹25,000 require purchase order PO match.`,
  },
  {
    id: "pol_returns_01",
    title: "Customer Returns & Exchange Operational Standard v2.1",
    category: "RETURNS_REFUNDS",
    content: `AXION RETURNS & EXCHANGE DECISION MATRIX
1. SIZING & FIT ISSUES:
   - VIP and Gold Tier customers: Offer instant one-click size exchange with priority zero-wait shipping.
   - If unworn with tags attached within 30 days: Approve exchange immediately. If size is in stock, reserve unit immediately.
2. DEFECTS & DAMAGE:
   - Escalate if claim exceeds ₹15,000 or customer has >3 defect claims in 60 days.
   - Otherwise issue direct replacement with free reverse pickup.
3. REFUND VS EXCHANGE RETENTION:
   - Promote size exchange or store credit + 5% bonus credit over cash refund to maintain retained revenue.`,
  },
];

export const MOCK_RISKS = [
  {
    id: "risk_01",
    title: "SKU-409 Stockout Imminent in 9 Days",
    department: "INVENTORY" as const,
    severity: "CRITICAL" as const,
    description: "Apex ANC Headphones daily velocity increased to 20 units/day. Current stock (180 units) will deplete by Sept 15.",
    suggestedAction: "Trigger emergency purchase order of 350 units with Supplier B (Bangalore FastTech) with 4-day lead time to prevent stockout.",
    impactScore: 94,
    timestamp: "12 mins ago",
  },
  {
    id: "risk_02",
    title: "Expense Policy Overrun Spikes in Sales Dept",
    department: "FINANCE" as const,
    severity: "HIGH" as const,
    description: "3 recent Mumbai travel accommodation claims exceed the ₹12,000 corporate ceiling by an average of 42%.",
    suggestedAction: "Enforce automated pre-trip booking integration with corporate rate partner portal.",
    impactScore: 78,
    timestamp: "45 mins ago",
  },
  {
    id: "risk_03",
    title: "Rising Return Rate on Velocity Pro UK 9",
    department: "CUSTOMER_OPS" as const,
    severity: "MEDIUM" as const,
    description: "Return rate spiked from 4.2% to 11.8% citing 'Runs small compared to standard sizing'.",
    suggestedAction: "Update product page sizing advisory to 'Order 0.5 size up' and auto-recommend UK 9.5 for exchanges.",
    impactScore: 68,
    timestamp: "2 hours ago",
  },
  {
    id: "risk_04",
    title: "Freight Carrier Delay in North Corridor",
    department: "SUPPLY_CHAIN" as const,
    severity: "LOW" as const,
    description: "Regional transit times extended by 24-36 hours due to monsoon weather advisories.",
    suggestedAction: "Auto-adjust promise delivery dates in checkout by +1 business day.",
    impactScore: 42,
    timestamp: "5 hours ago",
  },
];

export const MOCK_PRICING_INSIGHTS = [
  {
    id: "prc_01",
    sku: "SKU-409",
    productName: "Apex ANC Pro Wireless Headphones",
    currentPrice: 12999,
    recommendedPrice: 13999,
    competitorAvg: 14499,
    elasticityScore: 0.62,
    projectedDemand: "-3.5% volume, +8.1% revenue",
    projectedRevenue: "+₹1,82,000/mo net margin",
    confidenceScore: 92,
    reasoning: "High customer sentiment (4.8/5) and low price elasticity (0.62) allows a ₹1,000 upward calibration while remaining ₹500 below key market rival.",
  },
  {
    id: "prc_02",
    sku: "SKU-102",
    productName: "Axion Velocity Pro Running Shoes",
    currentPrice: 6499,
    recommendedPrice: 6199,
    competitorAvg: 6299,
    elasticityScore: 1.45,
    projectedDemand: "+18.2% volume, +11.4% gross revenue",
    projectedRevenue: "+₹94,000/mo margin",
    confidenceScore: 88,
    reasoning: "High price elasticity (1.45). A modest 4.6% discount captures volume in the competitive sports segment.",
  },
];

// ─────────────────────────────────────────────────────────────
// ENTERPRISE CYBER RISK INTELLIGENCE & TELEMETRY MOCK DATA
// ─────────────────────────────────────────────────────────────

import {
  CyberRiskOverview,
  CyberAssetItem,
  VulnerabilityItem,
  SecurityControlItem,
  SecurityEventItem,
  ThreatIntelligenceItem,
  RiskDriverItem,
  SecurityInvestmentOption,
  RiskTrendPoint,
  ComplianceFrameworkItem,
  ComplianceEvidenceItem,
  MultiFrameworkMappingRow,
  DiminishingReturnsPoint,
} from "./types";

export const MOCK_CYBER_OVERVIEW: CyberRiskOverview = {
  enterpriseScore: 72,
  scoreGrade: "ELEVATED_RISK",
  totalFinancialExposure: 38000000, // ₹3.8 Cr
  totalFinancialExposureFormatted: "₹3.8 Cr",
  expectedAnnualLoss: 21000000, // ₹2.1 Cr
  expectedAnnualLossFormatted: "₹2.1 Cr",
  potentialMaxLoss: 84000000, // ₹8.4 Cr
  potentialMaxLossFormatted: "₹8.4 Cr",
  incidentLikelihoodPercent: 17, // 17%
  controlEffectivenessPercent: 74, // 74%
  criticalAssetCount: 18,
  highRiskAssetCount: 7,
  totalMonitoredAssets: 1250,
  riskReductionOpportunity: 14000000, // ₹1.4 Cr
  riskReductionOpportunityFormatted: "₹1.4 Cr",
  lastAssessed: "Just now (Continuous Ingestion)",
  isSimulatedData: true,
};

export const MOCK_CYBER_ASSETS: CyberAssetItem[] = [
  {
    id: "asset_01",
    name: "Payment Gateway DB Cluster",
    assetType: "DATABASE",
    businessUnit: "Payments",
    criticalityScore: 10,
    technicalRiskScore: 82,
    internetExposed: true,
    environment: "PRODUCTION",
    ipOrHost: "10.142.18.4 (pg-cluster-prod.axion.internal)",
    dataSensitivity: "RESTRICTED",
    revenueDependency: "CRITICAL",
    downtimeCostPerHour: 1800000, // ₹18L/hr
    dataBreachPotential: 24000000, // ₹2.4 Cr
    incidentProbability: 0.17, // 17%
    controlEffectiveness: 0.58, // 58%
    potentialImpact: 24000000, // ₹2.4 Cr
    expectedAnnualLoss: 4080000, // ₹40.8L
    owner: "FinTech Core SecOps",
    status: "ACTIVE",
    vulnerabilitiesCount: 4,
    criticalVulnerabilitiesCount: 2,
  },
  {
    id: "asset_02",
    name: "Customer Auth & Session Vault",
    assetType: "AUTH_SERVER",
    businessUnit: "E-commerce",
    criticalityScore: 9,
    technicalRiskScore: 78,
    internetExposed: true,
    environment: "PRODUCTION",
    ipOrHost: "auth.axionplatform.com",
    dataSensitivity: "RESTRICTED",
    revenueDependency: "CRITICAL",
    downtimeCostPerHour: 1200000,
    dataBreachPotential: 18500000,
    incidentProbability: 0.15,
    controlEffectiveness: 0.62,
    potentialImpact: 18500000,
    expectedAnnualLoss: 2775000,
    owner: "IAM Engineering",
    status: "ACTIVE",
    vulnerabilitiesCount: 3,
    criticalVulnerabilitiesCount: 1,
  },
  {
    id: "asset_03",
    name: "Core E-Commerce API Gateway",
    assetType: "API_GATEWAY",
    businessUnit: "E-commerce",
    criticalityScore: 9,
    technicalRiskScore: 69,
    internetExposed: true,
    environment: "PRODUCTION",
    ipOrHost: "api.axionplatform.com",
    dataSensitivity: "CONFIDENTIAL",
    revenueDependency: "CRITICAL",
    downtimeCostPerHour: 950000,
    dataBreachPotential: 12000000,
    incidentProbability: 0.14,
    controlEffectiveness: 0.71,
    potentialImpact: 14500000,
    expectedAnnualLoss: 2030000,
    owner: "Platform Ingress Team",
    status: "ACTIVE",
    vulnerabilitiesCount: 5,
    criticalVulnerabilitiesCount: 1,
  },
  {
    id: "asset_04",
    name: "Cloud Storage Bucket (Customer PII & KYC)",
    assetType: "CLOUD_STORAGE",
    businessUnit: "Customer Operations",
    criticalityScore: 8,
    technicalRiskScore: 74,
    internetExposed: false,
    environment: "PRODUCTION",
    ipOrHost: "s3://axion-kyc-vault-in-south",
    dataSensitivity: "RESTRICTED",
    revenueDependency: "HIGH",
    downtimeCostPerHour: 400000,
    dataBreachPotential: 16000000,
    incidentProbability: 0.12,
    controlEffectiveness: 0.66,
    potentialImpact: 16000000,
    expectedAnnualLoss: 1920000,
    owner: "Data Governance",
    status: "ACTIVE",
    vulnerabilitiesCount: 2,
    criticalVulnerabilitiesCount: 1,
  },
  {
    id: "asset_05",
    name: "Corporate Active Directory & SSO",
    assetType: "AUTH_SERVER",
    businessUnit: "Corporate IT",
    criticalityScore: 9,
    technicalRiskScore: 64,
    internetExposed: false,
    environment: "INTERNAL",
    ipOrHost: "dc01.corp.axion.internal",
    dataSensitivity: "CONFIDENTIAL",
    revenueDependency: "HIGH",
    downtimeCostPerHour: 600000,
    dataBreachPotential: 9000000,
    incidentProbability: 0.11,
    controlEffectiveness: 0.79,
    potentialImpact: 11000000,
    expectedAnnualLoss: 1210000,
    owner: "IT Operations",
    status: "ACTIVE",
    vulnerabilitiesCount: 3,
    criticalVulnerabilitiesCount: 0,
  },
  {
    id: "asset_06",
    name: "Enterprise ERP & Finance Ledger",
    assetType: "ERP",
    businessUnit: "Finance",
    criticalityScore: 8,
    technicalRiskScore: 55,
    internetExposed: false,
    environment: "INTERNAL",
    ipOrHost: "erp-app.corp.axion.internal",
    dataSensitivity: "CONFIDENTIAL",
    revenueDependency: "HIGH",
    downtimeCostPerHour: 750000,
    dataBreachPotential: 8500000,
    incidentProbability: 0.08,
    controlEffectiveness: 0.82,
    potentialImpact: 9500000,
    expectedAnnualLoss: 760000,
    owner: "Finance Systems",
    status: "ACTIVE",
    vulnerabilitiesCount: 1,
    criticalVulnerabilitiesCount: 0,
  },
  {
    id: "asset_07",
    name: "Production Kubernetes Worker Nodes (Cluster-01)",
    assetType: "MICROSERVICE",
    businessUnit: "Cloud Infrastructure",
    criticalityScore: 9,
    technicalRiskScore: 71,
    internetExposed: false,
    environment: "PRODUCTION",
    ipOrHost: "k8s-worker-pool-mumbai",
    dataSensitivity: "CONFIDENTIAL",
    revenueDependency: "CRITICAL",
    downtimeCostPerHour: 1100000,
    dataBreachPotential: 11500000,
    incidentProbability: 0.13,
    controlEffectiveness: 0.73,
    potentialImpact: 13000000,
    expectedAnnualLoss: 1690000,
    owner: "DevOps & SRE",
    status: "ACTIVE",
    vulnerabilitiesCount: 4,
    criticalVulnerabilitiesCount: 1,
  },
  {
    id: "asset_08",
    name: "Executive & Employee Endpoints (1,200 Laptops)",
    assetType: "ENDPOINT",
    businessUnit: "Corporate IT",
    criticalityScore: 7,
    technicalRiskScore: 61,
    internetExposed: true,
    environment: "PRODUCTION",
    ipOrHost: "Fleet: CrowdStrike MDM Scope",
    dataSensitivity: "CONFIDENTIAL",
    revenueDependency: "MEDIUM",
    downtimeCostPerHour: 350000,
    dataBreachPotential: 7500000,
    incidentProbability: 0.16,
    controlEffectiveness: 0.87,
    potentialImpact: 8500000,
    expectedAnnualLoss: 1360000,
    owner: "Endpoint SecOps",
    status: "ACTIVE",
    vulnerabilitiesCount: 8,
    criticalVulnerabilitiesCount: 0,
  },
];

export const MOCK_VULNERABILITIES: VulnerabilityItem[] = [
  {
    id: "vuln_01",
    cveId: "CVE-2024-3094",
    title: "XZ Utils Backdoor / Remote Code Execution Exposure",
    cvssScore: 10.0,
    severity: "CRITICAL",
    exploitAvailable: true,
    patchAvailable: true,
    ageDays: 18,
    assetId: "asset_01",
    assetName: "Payment Gateway DB Cluster",
    remediationCost: 250000,
    riskContribution: 4200000, // ₹42L
    status: "OPEN",
  },
  {
    id: "vuln_02",
    cveId: "CVE-2024-21626",
    title: "runc Container Breakout & Privilege Escalation",
    cvssScore: 8.6,
    severity: "HIGH",
    exploitAvailable: true,
    patchAvailable: true,
    ageDays: 32,
    assetId: "asset_07",
    assetName: "Production Kubernetes Worker Nodes (Cluster-01)",
    remediationCost: 180000,
    riskContribution: 2100000,
    status: "IN_PROGRESS",
  },
  {
    id: "vuln_03",
    cveId: "CVE-2024-21413",
    title: "Microsoft Outlook Moniker Link Remote Code Execution",
    cvssScore: 9.8,
    severity: "CRITICAL",
    exploitAvailable: true,
    patchAvailable: true,
    ageDays: 12,
    assetId: "asset_08",
    assetName: "Executive & Employee Endpoints",
    remediationCost: 150000,
    riskContribution: 1600000,
    status: "OPEN",
  },
  {
    id: "vuln_04",
    cveId: "CVE-2024-27198",
    title: "JetBrains TeamCity Authentication Bypass in CI/CD",
    cvssScore: 9.8,
    severity: "CRITICAL",
    exploitAvailable: true,
    patchAvailable: true,
    ageDays: 24,
    assetId: "asset_03",
    assetName: "Core E-Commerce API Gateway",
    remediationCost: 200000,
    riskContribution: 2800000,
    status: "OPEN",
  },
];

export const MOCK_SECURITY_CONTROLS: SecurityControlItem[] = [
  {
    id: "ctrl_01",
    code: "CTRL-MFA",
    name: "Privileged & Employee Multi-Factor Authentication",
    category: "IAM",
    coveragePercent: 92,
    effectivenessPercent: 92,
    associatedRiskEal: 2800000,
    potentialRiskReduction: 3500000, // ₹35L
    annualCost: 500000, // ₹5L
    status: "ACTIVE",
    owner: "IAM Team",
    recommendation: "Enforce hardware FIDO2 keys for all 18 infrastructure administrators without SMS fallbacks.",
  },
  {
    id: "ctrl_02",
    code: "CTRL-EDR",
    name: "Endpoint Detection & Response (CrowdStrike Falcon)",
    category: "ENDPOINT",
    coveragePercent: 87,
    effectivenessPercent: 87,
    associatedRiskEal: 2200000,
    potentialRiskReduction: 2400000, // ₹24L
    annualCost: 1000000, // ₹10L
    status: "ACTIVE",
    owner: "SecOps",
    recommendation: "Extend sensor deployment across remaining 130 Linux staging and staging server nodes.",
  },
  {
    id: "ctrl_03",
    code: "CTRL-ENC",
    name: "End-to-End Database & Storage Encryption",
    category: "DATA_PROTECTION",
    coveragePercent: 95,
    effectivenessPercent: 95,
    associatedRiskEal: 1200000,
    potentialRiskReduction: 1800000,
    annualCost: 400000,
    status: "ACTIVE",
    owner: "Data Engineering",
    recommendation: "Rotate KMS master keys quarterly and automate envelope re-encryption.",
  },
  {
    id: "ctrl_04",
    code: "CTRL-PATCH",
    name: "Continuous Vulnerability & Patch Management",
    category: "VULN_MGMT",
    coveragePercent: 61,
    effectivenessPercent: 61,
    associatedRiskEal: 4600000,
    potentialRiskReduction: 4200000, // ₹42L
    annualCost: 800000, // ₹8L
    status: "PARTIAL",
    owner: "Infrastructure Team",
    recommendation: "Automate zero-downtime rolling patching for all critical CVSS 9.0+ vulnerabilities within 72 hours.",
  },
  {
    id: "ctrl_05",
    code: "CTRL-SEG",
    name: "Microsegmentation & Zero Trust Network Architecture",
    category: "NETWORK",
    coveragePercent: 42,
    effectivenessPercent: 42,
    associatedRiskEal: 3900000,
    potentialRiskReduction: 3800000, // ₹38L
    annualCost: 1200000, // ₹12L
    status: "DEFICIENT",
    owner: "Network SecOps",
    recommendation: "Isolate payment database subnet from shared corporate staging VLAN.",
  },
  {
    id: "ctrl_06",
    code: "CTRL-BACKUP",
    name: "Immutable Ransomware-Resistant Air-Gapped Backups",
    category: "BACKUP",
    coveragePercent: 88,
    effectivenessPercent: 88,
    associatedRiskEal: 1500000,
    potentialRiskReduction: 2100000,
    annualCost: 600000,
    status: "ACTIVE",
    owner: "SRE Storage Team",
    recommendation: "Test multi-region database recovery time objective (RTO < 4 hrs) monthly.",
  },
  {
    id: "ctrl_07",
    code: "CTRL-SIEM",
    name: "Next-Gen Cloud SIEM & Behavioral AI Analytics",
    category: "SIEM",
    coveragePercent: 78,
    effectivenessPercent: 78,
    associatedRiskEal: 2500000,
    potentialRiskReduction: 2700000, // ₹27L
    annualCost: 1500000, // ₹15L
    status: "ACTIVE",
    owner: "SOC Analysts",
    recommendation: "Integrate CSPM cloud audit trails directly into real-time correlation pipelines.",
  },
];

export const MOCK_SECURITY_EVENTS: SecurityEventItem[] = [
  {
    id: "evt_01",
    source: "VULN_SCANNER",
    eventType: "CRITICAL_CVE_DETECTED",
    severity: "CRITICAL",
    assetAffected: "Payment Gateway DB Cluster",
    details: "Critical vulnerability detected (CVE-2024-3094, CVSS 10.0) in upstream package.",
    riskDelta: 8,
    timeAgo: "12 sec ago",
    timestamp: "2026-09-17T00:26:48Z",
  },
  {
    id: "evt_02",
    source: "IAM",
    eventType: "MFA_POLICY_ENFORCED",
    severity: "LOW",
    assetAffected: "Corporate Active Directory",
    details: "MFA enabled for 12 privileged administrator accounts.",
    riskDelta: -5,
    timeAgo: "24 sec ago",
    timestamp: "2026-09-17T00:26:36Z",
  },
  {
    id: "evt_03",
    source: "THREAT_INTEL",
    eventType: "EXPLOIT_CAMPAIGN_MATCH",
    severity: "HIGH",
    assetAffected: "Core E-Commerce API Gateway",
    details: "New active in-the-wild exploit intelligence received for CVE-2024-27198 targeting API gateways.",
    riskDelta: 11,
    timeAgo: "41 sec ago",
    timestamp: "2026-09-17T00:26:19Z",
  },
  {
    id: "evt_04",
    source: "CSPM",
    eventType: "SECURITY_PATCH_DEPLOYED",
    severity: "LOW",
    assetAffected: "Customer Auth & Session Vault",
    details: "Critical security patch hotfix deployed successfully across auth instances.",
    riskDelta: -14,
    timeAgo: "1 min ago",
    timestamp: "2026-09-17T00:26:00Z",
  },
  {
    id: "evt_05",
    source: "SIEM",
    eventType: "BRUTE_FORCE_THROTTLED",
    severity: "MEDIUM",
    assetAffected: "Core E-Commerce API Gateway",
    details: "Throttled 4,200 credential stuffing requests from IP range 185.220.101.x via Cloudflare WAF.",
    riskDelta: 0,
    timeAgo: "2 mins ago",
    timestamp: "2026-09-17T00:25:00Z",
  },
  {
    id: "evt_06",
    source: "EDR",
    eventType: "MALWARE_CONTAINED",
    severity: "HIGH",
    assetAffected: "Employee Endpoints (DEV-LAP-041)",
    details: "Suspicious PowerShell invocation quarantined by CrowdStrike Falcon sensor.",
    riskDelta: -3,
    timeAgo: "4 mins ago",
    timestamp: "2026-09-17T00:23:00Z",
  },
];

export const MOCK_THREAT_INTEL: ThreatIntelligenceItem[] = [
  {
    id: "threat_01",
    threatActor: "FIN7 / Carbanak Variant",
    campaignName: "Retail API Ingress & Payment Skimming Wave",
    targetSector: "Retail, E-commerce, FinTech",
    cveReference: "CVE-2024-3094, CVE-2024-27198",
    severity: "CRITICAL",
    description: "Active automated scanning and exploit payload delivery targeting unpatched internet-facing API endpoints and database clusters.",
    active: true,
    detectedAt: "2026-09-16T18:00:00Z",
  },
  {
    id: "threat_02",
    threatActor: "Storm-0501",
    campaignName: "Multi-Cloud Hybrid Ransomware Extortion",
    targetSector: "Cross-Industry Cloud Infrastructure",
    cveReference: "CVE-2024-21626",
    severity: "HIGH",
    description: "Exploiting container misconfigurations and excessive IAM privileges to exfiltrate database backups prior to double extortion.",
    active: true,
    detectedAt: "2026-09-15T11:30:00Z",
  },
];

export const MOCK_RISK_DRIVERS: RiskDriverItem[] = [
  {
    id: "drv_01",
    title: "Internet-Facing Critical Vulnerability (CVE-2024-3094)",
    category: "VULNERABILITY",
    financialContribution: 4200000,
    financialContributionFormatted: "₹42L",
    assetName: "Payment Gateway DB Cluster",
    cveId: "CVE-2024-3094",
    controlDeficiency: "CTRL-PATCH (Patching at 61%)",
    remediation: "Deploy vendor hotfix patch within 24h & enable database subnet ingress firewall restriction.",
    priority: 1,
    percentageOfTotal: 37.5,
  },
  {
    id: "drv_02",
    title: "Privileged Infrastructure Accounts Lacking Hardware MFA",
    category: "IAM",
    financialContribution: 2800000,
    financialContributionFormatted: "₹28L",
    assetName: "Corporate Active Directory & Cloud IAM",
    controlDeficiency: "CTRL-MFA (Coverage at 92%, 18 admins unkeyed)",
    remediation: "Enforce mandatory FIDO2 hardware keys on all AWS/GCP root and production IAM accounts.",
    priority: 2,
    percentageOfTotal: 25.0,
  },
  {
    id: "drv_03",
    title: "Payment Database Direct Network Ingress Exposure",
    category: "NETWORK",
    financialContribution: 2400000,
    financialContributionFormatted: "₹24L",
    assetName: "Payment Gateway DB Cluster",
    controlDeficiency: "CTRL-SEG (Segmentation at 42%)",
    remediation: "Implement Zero Trust microsegmentation to isolate payment database to private VPC endpoints.",
    priority: 3,
    percentageOfTotal: 21.4,
  },
  {
    id: "drv_04",
    title: "Weak Staging-to-Production Network Segmentation",
    category: "NETWORK",
    financialContribution: 1800000,
    financialContributionFormatted: "₹18L",
    assetName: "Production Kubernetes Worker Nodes",
    controlDeficiency: "CTRL-SEG (Legacy cross-VPC peering)",
    remediation: "Decommission cross-environment peering links and enforce mTLS service mesh policies.",
    priority: 4,
    percentageOfTotal: 16.1,
  },
];

export const MOCK_SECURITY_INVESTMENTS: SecurityInvestmentOption[] = [
  {
    id: "inv_01",
    controlCode: "CTRL-MFA",
    title: "Enterprise FIDO2 Hardware MFA Enforcement",
    category: "IAM",
    cost: 500000, // ₹5L
    costFormatted: "₹5,00,000 (₹5L)",
    riskReduction: 3500000, // ₹35L
    riskReductionFormatted: "₹35,00,000 (₹35L)",
    netBenefit: 3000000,
    netBenefitFormatted: "₹30L",
    rosiPercent: 600, // ((35L - 5L) / 5L) * 100 = 600%
    paybackMonths: 1.7,
    implementationTimeWeeks: 2,
    complexity: "LOW",
    description: "Procure and mandate physical FIDO2 keys for all 18 root engineers and enforce conditional access policies.",
    mitigatesDrivers: ["Privileged Infrastructure Accounts Lacking Hardware MFA"],
  },
  {
    id: "inv_02",
    controlCode: "CTRL-PATCH",
    title: "Automated Continuous Vulnerability & Hotfix Pipeline",
    category: "PATCHING",
    cost: 800000, // ₹8L
    costFormatted: "₹8,00,000 (₹8L)",
    riskReduction: 4200000, // ₹42L
    riskReductionFormatted: "₹42,00,000 (₹42L)",
    netBenefit: 3400000,
    netBenefitFormatted: "₹34L",
    rosiPercent: 425, // ((42L - 8L) / 8L) * 100 = 425%
    paybackMonths: 2.3,
    implementationTimeWeeks: 3,
    complexity: "MEDIUM",
    description: "Automated patch orchestration with staging canary testing to eliminate critical CVEs in <48 hours.",
    mitigatesDrivers: ["Internet-Facing Critical Vulnerability (CVE-2024-3094)"],
  },
  {
    id: "inv_03",
    controlCode: "CTRL-SEG",
    title: "Zero Trust Network Microsegmentation & Policy Isolation",
    category: "NETWORK",
    cost: 1200000, // ₹12L
    costFormatted: "₹12,00,000 (₹12L)",
    riskReduction: 3800000, // ₹38L
    riskReductionFormatted: "₹38,00,000 (₹38L)",
    netBenefit: 2600000,
    netBenefitFormatted: "₹26L",
    rosiPercent: 217, // ((38L - 12L) / 12L) * 100 = 217%
    paybackMonths: 3.8,
    implementationTimeWeeks: 6,
    complexity: "HIGH",
    description: "Enforce granular Envoy service-mesh mTLS policies and isolate payment subnets from general traffic.",
    mitigatesDrivers: ["Payment Database Direct Network Ingress Exposure", "Weak Staging-to-Production Network Segmentation"],
  },
  {
    id: "inv_04",
    controlCode: "CTRL-EDR",
    title: "Full-Fleet EDR Expansion & 24/7 Managed Threat Hunting",
    category: "EDR",
    cost: 1000000, // ₹10L
    costFormatted: "₹10,00,000 (₹10L)",
    riskReduction: 2400000, // ₹24L
    riskReductionFormatted: "₹24,00,000 (₹24L)",
    netBenefit: 1400000,
    netBenefitFormatted: "₹14L",
    rosiPercent: 140, // ((24L - 10L) / 10L) * 100 = 140%
    paybackMonths: 5.0,
    implementationTimeWeeks: 4,
    complexity: "MEDIUM",
    description: "Deploy EDR sensors to 100% of staging nodes and engage 24/7 MDR SOC monitoring with 15-min SLA.",
    mitigatesDrivers: ["Exploit payloads targeting unmonitored host nodes"],
  },
  {
    id: "inv_05",
    controlCode: "CTRL-SIEM",
    title: "Next-Gen Cloud SIEM Behavioral Analytics Upgrade",
    category: "SIEM",
    cost: 1500000, // ₹15L
    costFormatted: "₹15,00,000 (₹15L)",
    riskReduction: 2700000, // ₹27L
    riskReductionFormatted: "₹27,00,000 (₹27L)",
    netBenefit: 1200000,
    netBenefitFormatted: "₹12L",
    rosiPercent: 80, // ((27L - 15L) / 15L) * 100 = 80%
    paybackMonths: 6.7,
    implementationTimeWeeks: 5,
    complexity: "MEDIUM",
    description: "Implement automated behavioral detection models across multi-cloud IAM and database audit streams.",
    mitigatesDrivers: ["Silent credential abuse and slow data exfiltration"],
  },
  {
    id: "inv_06",
    controlCode: "CTRL-CLOUD",
    title: "Automated Cloud Security Posture Management (CSPM)",
    category: "CLOUD",
    cost: 700000, // ₹7L
    costFormatted: "₹7,00,000 (₹7L)",
    riskReduction: 1900000, // ₹19L
    riskReductionFormatted: "₹19,00,000 (₹19L)",
    netBenefit: 1200000,
    netBenefitFormatted: "₹12L",
    rosiPercent: 171,
    paybackMonths: 4.4,
    implementationTimeWeeks: 2,
    complexity: "LOW",
    description: "Real-time automated scanning and auto-remediation for public S3 buckets, permissive security groups, and exposed secrets.",
    mitigatesDrivers: ["Misconfigured Cloud Storage & Insecure Policies"],
  },
];

export const MOCK_RISK_TRENDS: Record<"7D" | "30D" | "90D" | "1Y", RiskTrendPoint[]> = {
  "7D": [
    { date: "Day -6", label: "Sep 11", financialExposure: 3.5, expectedAnnualLoss: 1.9, riskScore: 68, controlEffectiveness: 76 },
    { date: "Day -5", label: "Sep 12", financialExposure: 3.6, expectedAnnualLoss: 1.95, riskScore: 69, controlEffectiveness: 75 },
    { date: "Day -4", label: "Sep 13", financialExposure: 3.6, expectedAnnualLoss: 1.98, riskScore: 70, controlEffectiveness: 75 },
    { date: "Day -3", label: "Sep 14", financialExposure: 3.7, expectedAnnualLoss: 2.02, riskScore: 71, controlEffectiveness: 74 },
    { date: "Day -2", label: "Sep 15", financialExposure: 3.75, expectedAnnualLoss: 2.06, riskScore: 71, controlEffectiveness: 74 },
    { date: "Day -1", label: "Sep 16", financialExposure: 3.8, expectedAnnualLoss: 2.1, riskScore: 72, controlEffectiveness: 74 },
    { date: "Today", label: "Sep 17", financialExposure: 3.8, expectedAnnualLoss: 2.1, riskScore: 72, controlEffectiveness: 74 },
  ],
  "30D": [
    { date: "Week 1", label: "Aug 18", financialExposure: 2.8, expectedAnnualLoss: 1.5, riskScore: 59, controlEffectiveness: 81 },
    { date: "Week 2", label: "Aug 25", financialExposure: 3.1, expectedAnnualLoss: 1.7, riskScore: 64, controlEffectiveness: 78 },
    { date: "Week 3", label: "Sep 01", financialExposure: 3.4, expectedAnnualLoss: 1.85, riskScore: 67, controlEffectiveness: 76 },
    { date: "Week 4", label: "Sep 08", financialExposure: 3.7, expectedAnnualLoss: 2.05, riskScore: 71, controlEffectiveness: 74 },
    { date: "Current", label: "Sep 17", financialExposure: 3.8, expectedAnnualLoss: 2.1, riskScore: 72, controlEffectiveness: 74 },
  ],
  "90D": [
    { date: "Month -3", label: "June", financialExposure: 2.4, expectedAnnualLoss: 1.3, riskScore: 52, controlEffectiveness: 84 },
    { date: "Month -2", label: "July", financialExposure: 2.8, expectedAnnualLoss: 1.5, riskScore: 60, controlEffectiveness: 80 },
    { date: "Month -1", label: "August", financialExposure: 3.2, expectedAnnualLoss: 1.75, riskScore: 66, controlEffectiveness: 77 },
    { date: "Current", label: "September", financialExposure: 3.8, expectedAnnualLoss: 2.1, riskScore: 72, controlEffectiveness: 74 },
  ],
  "1Y": [
    { date: "Q4 2025", label: "Q4 '25", financialExposure: 2.1, expectedAnnualLoss: 1.1, riskScore: 48, controlEffectiveness: 86 },
    { date: "Q1 2026", label: "Q1 '26", financialExposure: 2.4, expectedAnnualLoss: 1.3, riskScore: 54, controlEffectiveness: 83 },
    { date: "Q2 2026", label: "Q2 '26", financialExposure: 2.9, expectedAnnualLoss: 1.6, riskScore: 62, controlEffectiveness: 79 },
    { date: "Q3 2026", label: "Q3 '26", financialExposure: 3.8, expectedAnnualLoss: 2.1, riskScore: 72, controlEffectiveness: 74 },
  ],
};

export const MOCK_DIMINISHING_RETURNS_CURVE: DiminishingReturnsPoint[] = [
  { investment: 0, investmentFormatted: "₹0", projectedEal: 21000000, projectedEalFormatted: "₹2.1 Cr", riskReduction: 0, marginalBenefitPerLakh: 0, isOptimalSpendZone: false },
  { investment: 500000, investmentFormatted: "₹5L", projectedEal: 17500000, projectedEalFormatted: "₹1.75 Cr", riskReduction: 3500000, marginalBenefitPerLakh: 7.0, isOptimalSpendZone: false },
  { investment: 1300000, investmentFormatted: "₹13L", projectedEal: 13300000, projectedEalFormatted: "₹1.33 Cr", riskReduction: 7700000, marginalBenefitPerLakh: 5.25, isOptimalSpendZone: true },
  { investment: 2500000, investmentFormatted: "₹25L", projectedEal: 9500000, projectedEalFormatted: "₹95L", riskReduction: 11500000, marginalBenefitPerLakh: 3.16, isOptimalSpendZone: true },
  { investment: 4000000, investmentFormatted: "₹40L", projectedEal: 7100000, projectedEalFormatted: "₹71L", riskReduction: 13900000, marginalBenefitPerLakh: 1.6, isOptimalSpendZone: false },
  { investment: 8000000, investmentFormatted: "₹80L", projectedEal: 5900000, projectedEalFormatted: "₹59L", riskReduction: 15100000, marginalBenefitPerLakh: 0.3, isOptimalSpendZone: false },
];

export const MOCK_COMPLIANCE_FRAMEWORKS: ComplianceFrameworkItem[] = [
  {
    id: "fw_01",
    code: "NIST_CSF",
    name: "NIST Cybersecurity Framework",
    fullName: "National Institute of Standards and Technology CSF 2.0",
    version: "2.0",
    authority: "US Department of Commerce",
    totalControls: 108,
    compliantControls: 89,
    complianceScorePercent: 82.4,
    status: "AUDIT_READY",
    controls: [
      { id: "nist_01", controlCode: "PR.AC-1", title: "Identities and credentials are managed", requirement: "Centralized IAM lifecycle with hardware MFA enforcement.", axionControlCode: "CTRL-MFA", status: "COMPLIANT", evidenceNote: "IAM telemetry verifies 92% coverage." },
      { id: "nist_02", controlCode: "PR.DS-1", title: "Data-at-rest is protected", requirement: "AES-256 database and storage encryption.", axionControlCode: "CTRL-ENC", status: "COMPLIANT", evidenceNote: "PostgreSQL & S3 default SSE-KMS active." },
      { id: "nist_03", controlCode: "PR.IP-1", title: "Configuration baselines are maintained", requirement: "Patch and vulnerability remediation SLAs.", axionControlCode: "CTRL-PATCH", status: "PARTIALLY_COMPLIANT", evidenceNote: "Patching is at 61% coverage (3 critical CVEs open)." },
      { id: "nist_04", controlCode: "PR.AC-5", title: "Network integrity is protected", requirement: "Zero trust network segmentation.", axionControlCode: "CTRL-SEG", status: "PARTIALLY_COMPLIANT", evidenceNote: "Microsegmentation at 42% (Payment DB subnet pending)." },
    ],
  },
  {
    id: "fw_02",
    code: "ISO27001",
    name: "ISO/IEC 27001:2022",
    fullName: "Information Security Management System Standard",
    version: "2022",
    authority: "International Organization for Standardization",
    totalControls: 93,
    compliantControls: 78,
    complianceScorePercent: 83.8,
    status: "AUDIT_READY",
    controls: [
      { id: "iso_01", controlCode: "A.9.4.2", title: "User authentication password & token management", requirement: "Enforce MFA on remote and privileged access.", axionControlCode: "CTRL-MFA", status: "COMPLIANT", evidenceNote: "Okta & Active Directory telemetry validated." },
      { id: "iso_02", controlCode: "A.12.6.1", title: "Management of technical vulnerabilities", requirement: "Timely patching of security vulnerabilities.", axionControlCode: "CTRL-PATCH", status: "PARTIALLY_COMPLIANT", evidenceNote: "CVE-2024-3094 requires vendor hotfix." },
      { id: "iso_03", controlCode: "A.13.1.3", title: "Segregation in networks", requirement: "Network security zones and perimeter controls.", axionControlCode: "CTRL-SEG", status: "PARTIALLY_COMPLIANT", evidenceNote: "Subnet isolation required for PCI scope." },
    ],
  },
  {
    id: "fw_03",
    code: "CIS_CONTROLS",
    name: "CIS Critical Security Controls",
    fullName: "Center for Internet Security Controls v8",
    version: "v8",
    authority: "Center for Internet Security",
    totalControls: 153,
    compliantControls: 122,
    complianceScorePercent: 79.7,
    status: "ATTENTION_REQUIRED",
    controls: [
      { id: "cis_01", controlCode: "Control 6", title: "Access Control Management", requirement: "Multi-Factor authentication on all enterprise assets.", axionControlCode: "CTRL-MFA", status: "COMPLIANT", evidenceNote: "92% compliance across workforce." },
      { id: "cis_02", controlCode: "Control 7", title: "Continuous Vulnerability Management", requirement: "Automated vulnerability scanning & triage.", axionControlCode: "CTRL-PATCH", status: "PARTIALLY_COMPLIANT", evidenceNote: "Scanner integrated; patch cadence needs acceleration." },
      { id: "cis_03", controlCode: "Control 12", title: "Network Infrastructure Management", requirement: "Network segmentation and firewall auditing.", axionControlCode: "CTRL-SEG", status: "NON_COMPLIANT", evidenceNote: "Segmentation score is 42%." },
    ],
  },
  {
    id: "fw_04",
    code: "RBI_CSF",
    name: "RBI Cyber Security Framework",
    fullName: "Reserve Bank of India Cyber Security Framework for Financial Services",
    version: "2024",
    authority: "Reserve Bank of India",
    totalControls: 76,
    compliantControls: 67,
    complianceScorePercent: 88.1,
    status: "AUDIT_READY",
    controls: [
      { id: "rbi_01", controlCode: "Sec-3.1", title: "Protection of Customer Financial Data", requirement: "Zero plaintext storage of card/UPI credentials and tokenization.", axionControlCode: "CTRL-ENC", status: "COMPLIANT", evidenceNote: "PCI-DSS Level 1 tokenization active." },
      { id: "rbi_02", controlCode: "Sec-4.2", title: "24/7 Security Operations Center", requirement: "Real-time SIEM alerting on anomaly thresholds.", axionControlCode: "CTRL-SIEM", status: "COMPLIANT", evidenceNote: "CrowdStrike & SIEM real-time correlation active." },
      { id: "rbi_03", controlCode: "Sec-5.4", title: "Privileged Access Security", requirement: "Mandatory hardware MFA for financial transaction approvals.", axionControlCode: "CTRL-MFA", status: "COMPLIANT", evidenceNote: "100% compliant on payment switch." },
    ],
  },
  {
    id: "fw_05",
    code: "SEBI_CSCRF",
    name: "SEBI Cybersecurity & Cyber Resilience Framework",
    fullName: "Securities and Exchange Board of India CSCRF",
    version: "2024 Release",
    authority: "SEBI",
    totalControls: 84,
    compliantControls: 71,
    complianceScorePercent: 84.5,
    status: "AUDIT_READY",
    controls: [
      { id: "sebi_01", controlCode: "CSCRF-1.4", title: "Air-Gapped Immutable Backups", requirement: "Offline golden copy backups with 4-hour RTO.", axionControlCode: "CTRL-BACKUP", status: "COMPLIANT", evidenceNote: "AWS S3 Object Lock & Glacier immutable backup active." },
      { id: "sebi_02", controlCode: "CSCRF-2.2", title: "Vulnerability Remediation Timelines", requirement: "Critical vulnerabilities remediated in <72 hours.", axionControlCode: "CTRL-PATCH", status: "PARTIALLY_COMPLIANT", evidenceNote: "Average remediation time currently 96 hours." },
    ],
  },
];

export const MOCK_COMPLIANCE_EVIDENCE: ComplianceEvidenceItem[] = [
  {
    id: "ev_01",
    controlCode: "CTRL-MFA",
    controlName: "Multi-Factor Authentication",
    frameworkCode: "NIST_CSF",
    frameworkName: "NIST CSF 2.0 (PR.AC-1)",
    evidenceType: "IAM_TELEMETRY",
    description: "Automated Okta IAM telemetry log confirms 92% of active directory accounts and 100% of payment switch admins require biometric/hardware MFA.",
    telemetryRef: "iam://okta-prod-telemetry/audit-2026-09",
    lastVerified: "Today, 00:15 UTC",
    verifiedBy: "Autonomous Compliance Agent",
    status: "VERIFIED",
  },
  {
    id: "ev_02",
    controlCode: "CTRL-ENC",
    controlName: "Database & Storage Encryption",
    frameworkCode: "RBI_CSF",
    frameworkName: "RBI CSF (Sec-3.1)",
    evidenceType: "ENCRYPTION_KEY_AUDIT",
    description: "AWS CloudTrail verifies AES-256 KMS key rotation on all Payment Database volumes and KYC S3 Buckets.",
    telemetryRef: "kms://ap-south-1:axion-master-key-01",
    lastVerified: "Yesterday, 23:40 UTC",
    verifiedBy: "Autonomous Compliance Agent",
    status: "VERIFIED",
  },
  {
    id: "ev_03",
    controlCode: "CTRL-EDR",
    controlName: "Endpoint Detection & Response",
    frameworkCode: "ISO27001",
    frameworkName: "ISO 27001 (A.12.2.1)",
    evidenceType: "EDR_AGENT_STATUS",
    description: "CrowdStrike Falcon API validates 1,200/1,200 employee endpoints active with zero policy exemptions.",
    telemetryRef: "edr://crowdstrike-api/host-coverage",
    lastVerified: "Today, 00:05 UTC",
    verifiedBy: "Autonomous Compliance Agent",
    status: "VERIFIED",
  },
  {
    id: "ev_04",
    controlCode: "CTRL-BACKUP",
    controlName: "Immutable Backups",
    frameworkCode: "SEBI_CSCRF",
    frameworkName: "SEBI CSCRF (CSCRF-1.4)",
    evidenceType: "BACKUP_VERIFICATION",
    description: "Automated test restore script executed successfully; verified RTO of 2.8 hours and 100% SHA-256 checksum integrity.",
    telemetryRef: "s3://axion-glacier-vault/restore-test-run",
    lastVerified: "2 days ago",
    verifiedBy: "SRE Automation Agent",
    status: "VERIFIED",
  },
  {
    id: "ev_05",
    controlCode: "CTRL-PATCH",
    controlName: "Patch Management",
    frameworkCode: "CIS_CONTROLS",
    frameworkName: "CIS Controls v8 (Control 7)",
    evidenceType: "VULN_SCAN_LOG",
    description: "Qualys vulnerability scan detected 3 open critical CVEs exceeding 14-day remediation SLA.",
    telemetryRef: "scan://qualys-prod-cluster/run-88219",
    lastVerified: "Today, 00:20 UTC",
    verifiedBy: "SecOps Vulnerability Scanner",
    status: "DEFICIENT",
  },
];

export const MOCK_MULTI_FRAMEWORK_MAPPINGS: MultiFrameworkMappingRow[] = [
  {
    axionControl: "Multi-Factor Authentication",
    axionCode: "CTRL-MFA",
    nistCsf: "PR.AC-1",
    cisControls: "Control 6 (6.3, 6.5)",
    iso27001: "A.9.4.2",
    rbiCsf: "Sec-5.4",
    sebiCscrf: "CSCRF-2.1",
    coverageStatus: "FULL_COVERAGE",
    effectiveness: 92,
  },
  {
    axionControl: "Vulnerability & Patch Mgmt",
    axionCode: "CTRL-PATCH",
    nistCsf: "PR.IP-1, DE.CM-8",
    cisControls: "Control 7 (7.1 - 7.7)",
    iso27001: "A.12.6.1",
    rbiCsf: "Sec-2.3",
    sebiCscrf: "CSCRF-2.2",
    coverageStatus: "PARTIAL_COVERAGE",
    effectiveness: 61,
  },
  {
    axionControl: "Network Microsegmentation",
    axionCode: "CTRL-SEG",
    nistCsf: "PR.AC-5, PR.DS-5",
    cisControls: "Control 12 (12.1 - 12.4)",
    iso27001: "A.13.1.3",
    rbiCsf: "Sec-1.2",
    sebiCscrf: "CSCRF-3.1",
    coverageStatus: "DEFICIENT",
    effectiveness: 42,
  },
  {
    axionControl: "Endpoint Detection (EDR)",
    axionCode: "CTRL-EDR",
    nistCsf: "DE.CM-1, RS.AN-1",
    cisControls: "Control 10 (10.1 - 10.7)",
    iso27001: "A.12.2.1",
    rbiCsf: "Sec-4.1",
    sebiCscrf: "CSCRF-1.2",
    coverageStatus: "FULL_COVERAGE",
    effectiveness: 87,
  },
  {
    axionControl: "Data & Storage Encryption",
    axionCode: "CTRL-ENC",
    nistCsf: "PR.DS-1, PR.DS-2",
    cisControls: "Control 3 (3.11, 3.12)",
    iso27001: "A.10.1.1",
    rbiCsf: "Sec-3.1",
    sebiCscrf: "CSCRF-4.1",
    coverageStatus: "FULL_COVERAGE",
    effectiveness: 95,
  },
  {
    axionControl: "Immutable Backups",
    axionCode: "CTRL-BACKUP",
    nistCsf: "PR.IP-4, RC.RP-1",
    cisControls: "Control 11 (11.1 - 11.5)",
    iso27001: "A.12.3.1",
    rbiCsf: "Sec-6.1",
    sebiCscrf: "CSCRF-1.4",
    coverageStatus: "FULL_COVERAGE",
    effectiveness: 88,
  },
  {
    axionControl: "Cloud SIEM & Analytics",
    axionCode: "CTRL-SIEM",
    nistCsf: "DE.AE-2, DE.AE-3",
    cisControls: "Control 8 (8.1 - 8.12)",
    iso27001: "A.12.4.1",
    rbiCsf: "Sec-4.2",
    sebiCscrf: "CSCRF-1.1",
    coverageStatus: "FULL_COVERAGE",
    effectiveness: 78,
  },
];

